### ISSUE TITLE
Create and implement the main engine file

### ISSUE THREAD

**Issue by fardeenmohd** [vozhyk-/krar-project#3]
1. Make all the models from scenarios in domain description
      1.1. Fork model when releases statement occurs
      1.2. Fork model when more then one solution to logical formula (E.g. test it with satisfiable(formula, all_models = True))
      1.3. Remove model when Impossible statement occurs at the time of Action Occurence
      1.4. Remove model when Impossible statement occurs if logical formula holds at the time of Action Occurence
      1.5. Remove model when Observations are not the same as fluents in the model 
      1.6. Remove model when Action occurs but cannot be executed from domain description

**Comment by matrackif** [comment]
Engine functionality has been implemented, we need to test it. See [this issue](https://github.com/vozhyk-/krar-project/issues/8). I Expect only minor changes and bug fixes but who knows.
